language: scala
scala:
 - "2.11.7"
jdk:
 - oraclejdk8
sudo: false

services:
  - elasticsearch

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

env:
  - MAILGUN_API_KEY=notarealkey

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M coverage test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success: "sbt coveralls"
before_script:
before_script:
  - sleep 10
  - curl -XPUT 'http://127.0.0.1:9200/scoap3/'
